# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = ""
#[main.params]
#icon = "home"
#newtab = true

#icons located here https://tablericons.com/


[[social]]
identifier = "github"
name = "Union Website"
url = "https://www.imperialcollegeunion.org/activities/a-to-z/mountaineering"

[social.params]
icon = "IC-Union"


[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/ic_mountaineering/"


[social.params]
icon = "brand-instagram"



[[social]]
identifier = "email"
name = "Email"
url = "mailto:mountain@imperial.ac.uk"

[social.params]
icon = "send"